:concurrency: 5 # 并发数
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log # 输出的日志地址
:development:
  :concurrency: 5
:staging:
  :concurrency: 10
:production:
  :concurrency: 20
:queues:
  - default
  - mailer
  - common

